<a href="https://colab.research.google.com/github/jillianhaig/Project2_DS4002/blob/main/SCRIPTS/1data_creation_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! git clone https://github.com/jillianhaig/Project2_DS4002 # so we can access data loaded from shared github

fatal: destination path 'Project2_DS4002' already exists and is not an empty directory.

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df = pd.read_csv('/content/Project2_DS4002/DATA/hurr.atl.days.csv')

In [5]:
df.rename(columns={'  Number of days with hurricane in Atlantic  missing value -99 https://psl.noaa.gov/data/timeseries/month/': 'hurricane_days'}, inplace=True)

In [6]:
# Convert the date column to datetime format
df['date'] = pd.to_datetime(df['Date'])

# Filter the data to start from 1970
df_filtered = df[df['date'] >= '1970-01-01']

# Extract the year from the date column
df_filtered['year'] = df_filtered['date'].dt.year

# Group by year and sum the number of hurricane days
yearly_data = df_filtered.groupby('year')['hurricane_days'].sum().reset_index()

# Rename the columns for clarity
yearly_data.columns = ['Year', 'Hurricane_Days']

# Display the resulting yearly data
print(yearly_data)

    Year  Hurricane_Days
0   1970           13.25
1   1971           28.75
2   1972            6.25
3   1973           10.00
4   1974           14.25
5   1975           20.50
6   1976           25.50
7   1977            6.75
8   1978           13.50
9   1979           21.75
10  1980           38.25
11  1981           22.50
12  1982            5.75
13  1983            3.50
14  1984           18.25
15  1985           21.25
16  1986           10.50
17  1987            5.00
18  1988           21.25
19  1989           31.75
20  1990           26.75
21  1991            8.25
22  1992           16.00
23  1993            9.50
24  1994            7.25
25  1995           60.25
26  1996           45.00
27  1997            9.50
28  1998           48.50
29  1999           41.00
30  2000           32.75
31  2001           25.50
32  2002           10.75
33  2003           32.75
34  2004           45.50
35  2005           49.75
36  2006           21.25
37  2007           12.25
38  2008           30.50
39  2009           12.00
40  2010           38.50
41  2011           26.00
42  2012           28.50
43  2013            3.25
44  2014           17.75
45  2015           12.00
46  2016           27.75
47  2017           51.75
48  2018           27.50
49  2019           23.50
50  2020           35.25
51  2021           27.75
52  2022           22.00

<ipython-input-6-203050a7aa3f>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['year'] = df_filtered['date'].dt.year

In [7]:
df2 = pd.read_csv('/content/Project2_DS4002/DATA/annual-co2-emissions-per-country.csv')

In [8]:
df2 = df2[(df2['Entity'] == 'World') & (df2['Year'] >= 1970)]

In [9]:
df2.drop(columns=['Code'], inplace=True)

In [10]:
df2.rename(columns={'Annual COâ‚‚ emissions': 'CO2_emissions'}, inplace=True)

In [11]:
merged_df = pd.merge(yearly_data, df2, on='Year')

In [12]:
merged_df = merged_df.drop(columns=['Entity'])

In [13]:
merged_df.rename(columns={'Hurricane_Days': 'Atlantic_Hurricane_Days'}, inplace=True)

In [14]:
merged_df

    Year  Atlantic_Hurricane_Days  CO2_emissions
0   1970                    13.25   1.489816e+10
1   1971                    28.75   1.550279e+10
2   1972                     6.25   1.622344e+10
3   1973                    10.00   1.708350e+10
4   1974                    14.25   1.700938e+10
5   1975                    20.50   1.704998e+10
6   1976                    25.50   1.798524e+10
7   1977                     6.75   1.849465e+10
8   1978                    13.50   1.906396e+10
9   1979                    21.75   1.960300e+10
10  1980                    38.25   1.948244e+10
11  1981                    22.50   1.901695e+10
12  1982                     5.75   1.886537e+10
13  1983                     3.50   1.898590e+10
14  1984                    18.25   1.964173e+10
15  1985                    21.25   2.030513e+10
16  1986                    10.50   2.060752e+10
17  1987                     5.00   2.124578e+10
18  1988                    21.25   2.207738e+10
19  1989                    31.75   2.237897e+10
20  1990                    26.75   2.275270e+10
21  1991                     8.25   2.322948e+10
22  1992                    16.00   2.256720e+10
23  1993                     9.50   2.279835e+10
24  1994                     7.25   2.303478e+10
25  1995                    60.25   2.352449e+10
26  1996                    45.00   2.425016e+10
27  1997                     9.50   2.439595e+10
28  1998                    48.50   2.433094e+10
29  1999                    41.00   2.483350e+10
30  2000                    32.75   2.550129e+10
31  2001                    25.50   2.567493e+10
32  2002                    10.75   2.624829e+10
33  2003                    32.75   2.764865e+10
34  2004                    45.50   2.862019e+10
35  2005                    49.75   2.959210e+10
36  2006                    21.25   3.060577e+10
37  2007                    12.25   3.149974e+10
38  2008                    30.50   3.204190e+10
39  2009                    12.00   3.149326e+10
40  2010                    38.50   3.330633e+10
41  2011                    26.00   3.443647e+10
42  2012                    28.50   3.493545e+10
43  2013                     3.25   3.523247e+10
44  2014                    17.75   3.546620e+10
45  2015                    12.00   3.546321e+10
46  2016                    27.75   3.546003e+10
47  2017                    51.75   3.602546e+10
48  2018                    27.50   3.676694e+10
49  2019                    23.50   3.704010e+10
50  2020                    35.25   3.500774e+10
51  2021                    27.75   3.681654e+10
52  2022                    22.00   3.714979e+10

In [15]:
df3 = pd.read_csv('/content/Project2_DS4002/DATA/hurr.nepac.days.csv')

In [16]:
column_names = df3.columns.tolist()

print(column_names)

['Date', '  NE Pacific Hurricane days/month  missing value -99 https://psl.noaa.gov/data/timeseries/month/']

In [17]:
df3.rename(columns={'  NE Pacific Hurricane days/month  missing value -99 https://psl.noaa.gov/data/timeseries/month/': 'Pacific_Hurricane_Days'}, inplace=True)

In [18]:
df3.head()

         Date  Pacific_Hurricane_Days
0  1971-01-01                    0.00
1  1971-02-01                    0.00
2  1971-03-01                    0.00
3  1971-04-01                    0.00
4  1971-05-01                    2.25

In [19]:
df3['Date'] = pd.to_datetime(df3['Date'])

# Filter the DataFrame to only include data from 1971 onwards
df_filtered2 = df3[df3['Date'] >= '1971-01-01']

# Extract the year from the Date
df_filtered2['Year'] = df_filtered2['Date'].dt.year

# Group by Year and calculate the average
yearly_avg2 = df_filtered2.groupby('Year')['Pacific_Hurricane_Days'].sum().reset_index()

# Rename the columns for clarity
yearly_avg2.columns = ['Year', 'Pacific_Hurricane_Days']
df_3 = yearly_avg2

# Display the resulting yearly data
print(df_3)

    Year  Pacific_Hurricane_Days
0   1971                   38.50
1   1972                   33.75
2   1973                   28.50
3   1974                   22.75
4   1975                   26.75
5   1976                   27.25
6   1977                    5.25
7   1978                   51.50
8   1979                   13.75
9   1980                   22.75
10  1981                   18.25
11  1982                   39.25
12  1983                   47.75
13  1984                   46.25
14  1985                   49.75
15  1986                   28.75
16  1987                   29.50
17  1988                   29.50
18  1989                   27.25
19  1990                   58.25
20  1991                   44.00
21  1992                   65.50
22  1993                   50.75
23  1994                   33.00
24  1995                   22.25
25  1996                   13.00
26  1997                   33.50
27  1998                   33.00
28  1999                   23.50
29  2000                   16.75
30  2001                   18.50
31  2002                   26.00
32  2003                   11.00
33  2004                   14.00
34  2005                   23.50
35  2006                   34.00
36  2007                    8.75
37  2008                   19.00
38  2009                   23.00
39  2010                   11.50
40  2011                   26.75
41  2012                   21.50
42  2013                   14.50
43  2014                   44.50
44  2015                   62.25
45  2016                   38.50
46  2017                   20.00
47  2018                   68.25
48  2019                   16.75
49  2020                   14.25
50  2021                   21.50

In [20]:
merged_df2 = pd.merge(merged_df, df_3, on='Year')

In [21]:
merged_df2['Total_Hurricane_Days'] = merged_df2['Pacific_Hurricane_Days'] + merged_df2['Atlantic_Hurricane_Days']

In [22]:
merged_df2

,Year,Atlantic_Hurricane_Days,CO2_emissions,Pacific_Hurricane_Days,Total_Hurricane_Days
0,1971,28.75,1.550279e+10,38.50,67.25
1,1972,6.25,1.622344e+10,33.75,40.00
2,1973,10.00,1.708350e+10,28.50,38.50
3,1974,14.25,1.700938e+10,22.75,37.00
4,1975,20.50,1.704998e+10,26.75,47.25
5,1976,25.50,1.798524e+10,27.25,52.75
6,1977,6.75,1.849465e+10,5.25,12.00
7,1978,13.50,1.906396e+10,51.50,65.00
8,1979,21.75,1.960300e+10,13.75,35.50
9,1980,38.25,1.948244e+10,22.75,61.00
10,1981,22.50,1.901695e+10,18.25,40.75
11,1982,5.75,1.886537e+10,39.25,45.00
12,1983,3.50,1.898590e+10,47.75,51.25
13,1984,18.25,1.964173e+10,46.25,64.50
14,1985,21.25,2.030513e+10,49.75,71.00
15,1986,10.50,2.060752e+10,28.75,39.25
16,1987,5.00,2.124578e+10,29.50,34.50
17,1988,21.25,2.207738e+10,29.50,50.75
18,1989,31.75,2.237897e+10,27.25,59.00
19,1990,26.75,2.275270e+10,58.25,85.00
20,1991,8.25,2.322948e+10,44.00,52.25
21,1992,16.00,2.256720e+10,65.50,81.50
22,1993,9.50,2.279835e+10,50.75,60.25
23,1994,7.25,2.303478e+10,33.00,40.25
24,1995,60.25,2.352449e+10,22.25,82.50
25,1996,45.00,2.425016e+10,13.00,58.00
26,1997,9.50,2.439595e+10,33.50,43.00
27,1998,48.50,2.433094e+10,33.00,81.50
28,1999,41.00,2.483350e+10,23.50,64.50
29,2000,32.75,2.550129e+10,16.75,49.50
30,2001,25.50,2.567493e+10,18.50,44.00
31,2002,10.75,2.624829e+10,26.00,36.75
32,2003,32.75,2.764865e+10,11.00,43.75
33,2004,45.50,2.862019e+10,14.00,59.50
34,2005,49.75,2.959210e+10,23.50,73.25
35,2006,21.25,3.060577e+10,34.00,55.25
36,2007,12.25,3.149974e+10,8.75,21.00
37,2008,30.50,3.204190e+10,19.00,49.50
38,2009,12.00,3.149326e+10,23.00,35.00
39,2010,38.50,3.330633e+10,11.50,50.00
40,2011,26.00,3.443647e+10,26.75,52.75
41,2012,28.50,3.493545e+10,21.50,50.00
42,2013,3.25,3.523247e+10,14.50,17.75
43,2014,17.75,3.546620e+10,44.50,62.25
44,2015,12.00,3.546321e+10,62.25,74.25
45,2016,27.75,3.546003e+10,38.50,66.25
46,2017,51.75,3.602546e+10,20.00,71.75
47,2018,27.50,3.676694e+10,68.25,95.75
48,2019,23.50,3.704010e+10,16.75,40.25
49,2020,35.25,3.500774e+10,14.25,49.50
50,2021,27.75,3.681654e+10,21.50,49.25

In [23]:
merged_df2

,Year,Atlantic_Hurricane_Days,CO2_emissions,Pacific_Hurricane_Days,Total_Hurricane_Days
0,1971,28.75,1.550279e+10,38.50,67.25
1,1972,6.25,1.622344e+10,33.75,40.00
2,1973,10.00,1.708350e+10,28.50,38.50
3,1974,14.25,1.700938e+10,22.75,37.00
4,1975,20.50,1.704998e+10,26.75,47.25
5,1976,25.50,1.798524e+10,27.25,52.75
6,1977,6.75,1.849465e+10,5.25,12.00
7,1978,13.50,1.906396e+10,51.50,65.00
8,1979,21.75,1.960300e+10,13.75,35.50
9,1980,38.25,1.948244e+10,22.75,61.00
10,1981,22.50,1.901695e+10,18.25,40.75
11,1982,5.75,1.886537e+10,39.25,45.00
12,1983,3.50,1.898590e+10,47.75,51.25
13,1984,18.25,1.964173e+10,46.25,64.50
14,1985,21.25,2.030513e+10,49.75,71.00
15,1986,10.50,2.060752e+10,28.75,39.25
16,1987,5.00,2.124578e+10,29.50,34.50
17,1988,21.25,2.207738e+10,29.50,50.75
18,1989,31.75,2.237897e+10,27.25,59.00
19,1990,26.75,2.275270e+10,58.25,85.00
20,1991,8.25,2.322948e+10,44.00,52.25
21,1992,16.00,2.256720e+10,65.50,81.50
22,1993,9.50,2.279835e+10,50.75,60.25
23,1994,7.25,2.303478e+10,33.00,40.25
24,1995,60.25,2.352449e+10,22.25,82.50
25,1996,45.00,2.425016e+10,13.00,58.00
26,1997,9.50,2.439595e+10,33.50,43.00
27,1998,48.50,2.433094e+10,33.00,81.50
28,1999,41.00,2.483350e+10,23.50,64.50
29,2000,32.75,2.550129e+10,16.75,49.50
30,2001,25.50,2.567493e+10,18.50,44.00
31,2002,10.75,2.624829e+10,26.00,36.75
32,2003,32.75,2.764865e+10,11.00,43.75
33,2004,45.50,2.862019e+10,14.00,59.50
34,2005,49.75,2.959210e+10,23.50,73.25
35,2006,21.25,3.060577e+10,34.00,55.25
36,2007,12.25,3.149974e+10,8.75,21.00
37,2008,30.50,3.204190e+10,19.00,49.50
38,2009,12.00,3.149326e+10,23.00,35.00
39,2010,38.50,3.330633e+10,11.50,50.00
40,2011,26.00,3.443647e+10,26.75,52.75
41,2012,28.50,3.493545e+10,21.50,50.00
42,2013,3.25,3.523247e+10,14.50,17.75
43,2014,17.75,3.546620e+10,44.50,62.25
44,2015,12.00,3.546321e+10,62.25,74.25
45,2016,27.75,3.546003e+10,38.50,66.25
46,2017,51.75,3.602546e+10,20.00,71.75
47,2018,27.50,3.676694e+10,68.25,95.75
48,2019,23.50,3.704010e+10,16.75,40.25
49,2020,35.25,3.500774e+10,14.25,49.50
50,2021,27.75,3.681654e+10,21.50,49.25

In [24]:
df_pop = pd.read_csv('/content/Project2_DS4002/DATA/population (1).csv')

In [25]:
df_pop.rename(columns={'Population (historical)': 'Population'}, inplace=True)
df_pop.drop(columns=['Code'], inplace=True)

In [26]:
population_df = df_pop[(df_pop['Entity'] == 'World') & (df_pop['Year'] >= 1971) & (df_pop['Year'] <= 2021)]
population_df.drop(columns=['Entity'], inplace=True)

<ipython-input-26-f8c95e4d70c8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population_df.drop(columns=['Entity'], inplace=True)

In [27]:
merged_df3 = pd.merge(merged_df2, population_df, on='Year')
merged_df3

,Year,Atlantic_Hurricane_Days,CO2_emissions,Pacific_Hurricane_Days,Total_Hurricane_Days,Population
0,1971,28.75,1.550279e+10,38.50,67.25,3769847834
1,1972,6.25,1.622344e+10,33.75,40.00,3844917687
2,1973,10.00,1.708350e+10,28.50,38.50,3920805030
3,1974,14.25,1.700938e+10,22.75,37.00,3996416108
4,1975,20.50,1.704998e+10,26.75,47.25,4070735264
5,1976,25.50,1.798524e+10,27.25,52.75,4144246391
6,1977,6.75,1.849465e+10,5.25,12.00,4217863819
7,1978,13.50,1.906396e+10,51.50,65.00,4292097508
8,1979,21.75,1.960300e+10,13.75,35.50,4368539472
9,1980,38.25,1.948244e+10,22.75,61.00,4447606208
10,1981,22.50,1.901695e+10,18.25,40.75,4528777285
11,1982,5.75,1.886537e+10,39.25,45.00,4612673436
12,1983,3.50,1.898590e+10,47.75,51.25,4697327604
13,1984,18.25,1.964173e+10,46.25,64.50,4782175500
14,1985,21.25,2.030513e+10,49.75,71.00,4868943460
15,1986,10.50,2.060752e+10,28.75,39.25,4958072822
16,1987,5.00,2.124578e+10,29.50,34.50,5049746378
17,1988,21.25,2.207738e+10,29.50,50.75,5141992550
18,1989,31.75,2.237897e+10,27.25,59.00,5234431714
19,1990,26.75,2.275270e+10,58.25,85.00,5327803075
20,1991,8.25,2.322948e+10,44.00,52.25,5418735879
21,1992,16.00,2.256720e+10,65.50,81.50,5505989821
22,1993,9.50,2.279835e+10,50.75,60.25,5591544841
23,1994,7.25,2.303478e+10,33.00,40.25,5675551281
24,1995,60.25,2.352449e+10,22.25,82.50,5758878997
25,1996,45.00,2.425016e+10,13.00,58.00,5842055726
26,1997,9.50,2.439595e+10,33.50,43.00,5924787787
27,1998,48.50,2.433094e+10,33.00,81.50,6007066714
28,1999,41.00,2.483350e+10,23.50,64.50,6089006330
29,2000,32.75,2.550129e+10,16.75,49.50,6171703018
30,2001,25.50,2.567493e+10,18.50,44.00,6254936479
31,2002,10.75,2.624829e+10,26.00,36.75,6337730319
32,2003,32.75,2.764865e+10,11.00,43.75,6420361649
33,2004,45.50,2.862019e+10,14.00,59.50,6503377778
34,2005,49.75,2.959210e+10,23.50,73.25,6586970145
35,2006,21.25,3.060577e+10,34.00,55.25,6671452018
36,2007,12.25,3.149974e+10,8.75,21.00,6757308750
37,2008,30.50,3.204190e+10,19.00,49.50,6844457675
38,2009,12.00,3.149326e+10,23.00,35.00,6932766459
39,2010,38.50,3.330633e+10,11.50,50.00,7021732131
40,2011,26.00,3.443647e+10,26.75,52.75,7110923797
41,2012,28.50,3.493545e+10,21.50,50.00,7201202531
42,2013,3.25,3.523247e+10,14.50,17.75,7291793608
43,2014,17.75,3.546620e+10,44.50,62.25,7381616239
44,2015,12.00,3.546321e+10,62.25,74.25,7470491904
45,2016,27.75,3.546003e+10,38.50,66.25,7558554580
46,2017,51.75,3.602546e+10,20.00,71.75,7645618013
47,2018,27.50,3.676694e+10,68.25,95.75,7729902724
48,2019,23.50,3.704010e+10,16.75,40.25,7811293714
49,2020,35.25,3.500774e+10,14.25,49.50,7887001284
50,2021,27.75,3.681654e+10,21.50,49.25,7954448405

In [81]:
sealevel_df = pd.read_csv('/content/Project2_DS4002/DATA/sea-level_fig-1.csv')

In [82]:
sealevel_df.rename(columns={'Figure 1. Global Average Absolute Sea Level Change, 1880-2023': 'Year'}, inplace=True)

In [83]:
dfsea_dropped = sealevel_df.drop(sealevel_df.index[:5])

In [84]:
column_names = dfsea_dropped.columns.tolist()

# Display the column names
print(column_names)

['Year', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

In [85]:
dfsea_dropped.rename(columns={'Unnamed: 1': 'CSIRO_Adjusted_SeaLevel_Inch'}, inplace=True)

In [86]:
dfsea_dropped.drop(columns=['Unnamed: 2'], inplace=True)

In [87]:
dfsea_dropped.drop(columns=['Unnamed: 3'], inplace=True)

In [88]:
dfsea_dropped.drop(columns=['Unnamed: 4'], inplace=True)

In [89]:
dfsea_dropped = dfsea_dropped.drop(dfsea_dropped.index[:1])

In [90]:
dfsea_dropped['Year'] = dfsea_dropped['Year'].astype(int)

In [91]:
sealevel_filtered = dfsea_dropped[(dfsea_dropped['Year'] >= 1971) & (dfsea_dropped['Year'] <= 2021)]

In [92]:
sealevel_filtered

     Year CSIRO_Adjusted_SeaLevel_Inch
97   1971                  4.881889759
98   1972                  5.240157475
99   1973                  5.003937003
100  1974                  5.472440939
101  1975                  5.409448813
102  1976                  5.370078735
103  1977                  5.303149601
104  1978                  5.555118105
105  1979                  5.362204719
106  1980                  5.598425191
107  1981                  6.086614167
108  1982                  5.858267711
109  1983                  6.188976372
110  1984                  6.153543301
111  1985                   5.74803149
112  1986                  5.771653537
113  1987                  5.795275585
114  1988                  5.980314955
115  1989                  6.157480309
116  1990                   6.24803149
117  1991                  6.346456686
118  1992                  6.374015742
119  1993                    6.3031496
120  1994                  6.507874009
121  1995                  6.622047237
122  1996                   6.78346456
123  1997                  7.059055111
124  1998                  6.669291332
125  1999                  7.003937001
126  2000                  7.055118103
127  2001                  7.271653536
128  2002                  7.366141725
129  2003                  7.728346449
130  2004                  7.712598417
131  2005                  7.716535425
132  2006                  7.885826764
133  2007                  7.960629913
134  2008                  8.303149598
135  2009                  8.531496054
136  2010                   8.83464566
137  2011                  8.897637786
138  2012                  9.244094479
139  2013                  8.913385818
140  2014                  8.717314463
141  2015                  9.061105473
142  2016                  9.193601372
143  2017                  9.242845802
144  2018                  9.340091693
145  2019                  9.594329444
146  2020                  9.699874064
147  2021                  9.886687548

In [93]:
merged_df4 = pd.merge(merged_df3, sealevel_filtered, on='Year')
merged_df4

,Year,Atlantic_Hurricane_Days,CO2_emissions,Pacific_Hurricane_Days,Total_Hurricane_Days,Population,CSIRO_Adjusted_SeaLevel_Inch
0,1971,28.75,1.550279e+10,38.50,67.25,3769847834,4.881889759
1,1972,6.25,1.622344e+10,33.75,40.00,3844917687,5.240157475
2,1973,10.00,1.708350e+10,28.50,38.50,3920805030,5.003937003
3,1974,14.25,1.700938e+10,22.75,37.00,3996416108,5.472440939
4,1975,20.50,1.704998e+10,26.75,47.25,4070735264,5.409448813
5,1976,25.50,1.798524e+10,27.25,52.75,4144246391,5.370078735
6,1977,6.75,1.849465e+10,5.25,12.00,4217863819,5.303149601
7,1978,13.50,1.906396e+10,51.50,65.00,4292097508,5.555118105
8,1979,21.75,1.960300e+10,13.75,35.50,4368539472,5.362204719
9,1980,38.25,1.948244e+10,22.75,61.00,4447606208,5.598425191
10,1981,22.50,1.901695e+10,18.25,40.75,4528777285,6.086614167
11,1982,5.75,1.886537e+10,39.25,45.00,4612673436,5.858267711
12,1983,3.50,1.898590e+10,47.75,51.25,4697327604,6.188976372
13,1984,18.25,1.964173e+10,46.25,64.50,4782175500,6.153543301
14,1985,21.25,2.030513e+10,49.75,71.00,4868943460,5.74803149
15,1986,10.50,2.060752e+10,28.75,39.25,4958072822,5.771653537
16,1987,5.00,2.124578e+10,29.50,34.50,5049746378,5.795275585
17,1988,21.25,2.207738e+10,29.50,50.75,5141992550,5.980314955
18,1989,31.75,2.237897e+10,27.25,59.00,5234431714,6.157480309
19,1990,26.75,2.275270e+10,58.25,85.00,5327803075,6.24803149
20,1991,8.25,2.322948e+10,44.00,52.25,5418735879,6.346456686
21,1992,16.00,2.256720e+10,65.50,81.50,5505989821,6.374015742
22,1993,9.50,2.279835e+10,50.75,60.25,5591544841,6.3031496
23,1994,7.25,2.303478e+10,33.00,40.25,5675551281,6.507874009
24,1995,60.25,2.352449e+10,22.25,82.50,5758878997,6.622047237
25,1996,45.00,2.425016e+10,13.00,58.00,5842055726,6.78346456
26,1997,9.50,2.439595e+10,33.50,43.00,5924787787,7.059055111
27,1998,48.50,2.433094e+10,33.00,81.50,6007066714,6.669291332
28,1999,41.00,2.483350e+10,23.50,64.50,6089006330,7.003937001
29,2000,32.75,2.550129e+10,16.75,49.50,6171703018,7.055118103
30,2001,25.50,2.567493e+10,18.50,44.00,6254936479,7.271653536
31,2002,10.75,2.624829e+10,26.00,36.75,6337730319,7.366141725
32,2003,32.75,2.764865e+10,11.00,43.75,6420361649,7.728346449
33,2004,45.50,2.862019e+10,14.00,59.50,6503377778,7.712598417
34,2005,49.75,2.959210e+10,23.50,73.25,6586970145,7.716535425
35,2006,21.25,3.060577e+10,34.00,55.25,6671452018,7.885826764
36,2007,12.25,3.149974e+10,8.75,21.00,6757308750,7.960629913
37,2008,30.50,3.204190e+10,19.00,49.50,6844457675,8.303149598
38,2009,12.00,3.149326e+10,23.00,35.00,6932766459,8.531496054
39,2010,38.50,3.330633e+10,11.50,50.00,7021732131,8.83464566
40,2011,26.00,3.443647e+10,26.75,52.75,7110923797,8.897637786
41,2012,28.50,3.493545e+10,21.50,50.00,7201202531,9.244094479
42,2013,3.25,3.523247e+10,14.50,17.75,7291793608,8.913385818
43,2014,17.75,3.546620e+10,44.50,62.25,7381616239,8.717314463
44,2015,12.00,3.546321e+10,62.25,74.25,7470491904,9.061105473
45,2016,27.75,3.546003e+10,38.50,66.25,7558554580,9.193601372
46,2017,51.75,3.602546e+10,20.00,71.75,7645618013,9.242845802
47,2018,27.50,3.676694e+10,68.25,95.75,7729902724,9.340091693
48,2019,23.50,3.704010e+10,16.75,40.25,7811293714,9.594329444
49,2020,35.25,3.500774e+10,14.25,49.50,7887001284,9.699874064
50,2021,27.75,3.681654e+10,21.50,49.25,7954448405,9.886687548

In [101]:
surface_df = pd.read_csv('/content/Project2_DS4002/DATA/Annual_Surface_Temperature_Change.csv')

In [102]:
column_names = surface_df.columns.tolist()

# Display the column names
print(column_names)

['ObjectId', 'Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS_Code', 'CTS_Name', 'CTS_Full_Descriptor', 'F1961', 'F1962', 'F1963', 'F1964', 'F1965', 'F1966', 'F1967', 'F1968', 'F1969', 'F1970', 'F1971', 'F1972', 'F1973', 'F1974', 'F1975', 'F1976', 'F1977', 'F1978', 'F1979', 'F1980', 'F1981', 'F1982', 'F1983', 'F1984', 'F1985', 'F1986', 'F1987', 'F1988', 'F1989', 'F1990', 'F1991', 'F1992', 'F1993', 'F1994', 'F1995', 'F1996', 'F1997', 'F1998', 'F1999', 'F2000', 'F2001', 'F2002', 'F2003', 'F2004', 'F2005', 'F2006', 'F2007', 'F2008', 'F2009', 'F2010', 'F2011', 'F2012', 'F2013', 'F2014', 'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020', 'F2021', 'F2022']

In [104]:
surface_df.drop(columns=['ObjectId'],inplace=True)

In [105]:
surface_df.drop(columns=['ISO2'],inplace=True)

In [106]:
surface_df.drop(columns=['ISO3'],inplace=True)

In [107]:
surface_df.drop(columns=['Indicator'],inplace=True)

In [108]:
surface_df.drop(columns=['Unit'],inplace=True)

In [109]:
surface_df.drop(columns=['Source'],inplace=True)

In [110]:
surface_df.drop(columns=['CTS_Code'],inplace=True)

In [111]:
surface_df.drop(columns=['CTS_Name'],inplace=True)

In [112]:
surface_df.drop(columns=['CTS_Full_Descriptor'],inplace=True)

In [114]:
surface_filtered = surface_df[surface_df['Country'] == 'World']

In [118]:
surface_filtered.head()

,Country,F1961,F1962,F1963,F1964,F1965,F1966,F1967,F1968,F1969,...,F2013,F2014,F2015,F2016,F2017,F2018,F2019,F2020,F2021,F2022
221,World,0.211,0.038,0.168,-0.246,-0.223,0.201,-0.117,-0.126,-0.092,...,1.016,1.053,1.412,1.66,1.429,1.29,1.444,1.711,1.447,1.394