<a href="https://colab.research.google.com/github/jillianhaig/Project2_DS4002/blob/main/SCRIPTS/1data_creation_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/jillianhaig/Project2_DS4002 # so we can access data loaded from shared github

Cloning into 'Project2_DS4002'...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 112 (delta 42), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (112/112), 1021.86 KiB | 3.48 MiB/s, done.
Resolving deltas: 100% (42/42), done.

In [2]:
# import necessary packages
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [6]:
# import atlantic ocean hurricane data
df = pd.read_csv('/content/Project2_DS4002/DATA/Individual Datasets/hurr.atl.days.csv')

In [7]:
# rename column for clarity
df.rename(columns={'  Number of days with hurricane in Atlantic  missing value -99 https://psl.noaa.gov/data/timeseries/month/': 'hurricane_days'}, inplace=True)

In [8]:
# change the date column to datetime format
df['date'] = pd.to_datetime(df['Date'])

# filter the data to start from 1970
df_filtered = df[df['date'] >= '1971-01-01']

# get the year from the date column and group by year and sum of hurricane days
df_filtered['year'] = df_filtered['date'].dt.year
yearly_data = df_filtered.groupby('year')['hurricane_days'].sum().reset_index()

# rename the columns for clarity
yearly_data.columns = ['Year', 'Hurricane_Days']

<ipython-input-8-df72cc326e14>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['year'] = df_filtered['date'].dt.year

In [9]:
# load second dataset for co2 emissions
df2 = pd.read_csv('/content/Project2_DS4002/DATA/Individual Datasets/annual-co2-emissions-per-country.csv')

In [10]:
# filter for 1971 and later
df2 = df2[(df2['Entity'] == 'World') & (df2['Year'] >= 1971)]

In [11]:
# drop extraneous column
df2.drop(columns=['Code'], inplace=True)

In [12]:
# rename column for clarity
df2.rename(columns={'Annual COâ‚‚ emissions': 'CO2_emissions'}, inplace=True)

In [13]:
# merge first 2 datasets
merged_df = pd.merge(yearly_data, df2, on='Year')

In [14]:
# drop column (not needed)
merged_df = merged_df.drop(columns=['Entity'])

In [15]:
# rename columns
merged_df.rename(columns={'Hurricane_Days': 'Atlantic_Hurricane_Days'}, inplace=True)

In [16]:
merged_df

    Year  Atlantic_Hurricane_Days  CO2_emissions
0   1971                    28.75   1.550279e+10
1   1972                     6.25   1.622344e+10
2   1973                    10.00   1.708350e+10
3   1974                    14.25   1.700938e+10
4   1975                    20.50   1.704998e+10
5   1976                    25.50   1.798524e+10
6   1977                     6.75   1.849465e+10
7   1978                    13.50   1.906396e+10
8   1979                    21.75   1.960300e+10
9   1980                    38.25   1.948244e+10
10  1981                    22.50   1.901695e+10
11  1982                     5.75   1.886537e+10
12  1983                     3.50   1.898590e+10
13  1984                    18.25   1.964173e+10
14  1985                    21.25   2.030513e+10
15  1986                    10.50   2.060752e+10
16  1987                     5.00   2.124578e+10
17  1988                    21.25   2.207738e+10
18  1989                    31.75   2.237897e+10
19  1990                    26.75   2.275270e+10
20  1991                     8.25   2.322948e+10
21  1992                    16.00   2.256720e+10
22  1993                     9.50   2.279835e+10
23  1994                     7.25   2.303478e+10
24  1995                    60.25   2.352449e+10
25  1996                    45.00   2.425016e+10
26  1997                     9.50   2.439595e+10
27  1998                    48.50   2.433094e+10
28  1999                    41.00   2.483350e+10
29  2000                    32.75   2.550129e+10
30  2001                    25.50   2.567493e+10
31  2002                    10.75   2.624829e+10
32  2003                    32.75   2.764865e+10
33  2004                    45.50   2.862019e+10
34  2005                    49.75   2.959210e+10
35  2006                    21.25   3.060577e+10
36  2007                    12.25   3.149974e+10
37  2008                    30.50   3.204190e+10
38  2009                    12.00   3.149326e+10
39  2010                    38.50   3.330633e+10
40  2011                    26.00   3.443647e+10
41  2012                    28.50   3.493545e+10
42  2013                     3.25   3.523247e+10
43  2014                    17.75   3.546620e+10
44  2015                    12.00   3.546321e+10
45  2016                    27.75   3.546003e+10
46  2017                    51.75   3.602546e+10
47  2018                    27.50   3.676694e+10
48  2019                    23.50   3.704010e+10
49  2020                    35.25   3.500774e+10
50  2021                    27.75   3.681654e+10
51  2022                    22.00   3.714979e+10

In [27]:
# load next dataset for pacific ocean hurricane data
df3 = pd.read_csv('/content/Project2_DS4002/DATA/Individual Datasets/hurr.nepac.days.csv')

In [28]:
# find column names
column_names = df3.columns.tolist()

print(column_names)

['Date', '  NE Pacific Hurricane days/month  missing value -99 https://psl.noaa.gov/data/timeseries/month/']

In [29]:
# rename column for clarity
df3.rename(columns={'  NE Pacific Hurricane days/month  missing value -99 https://psl.noaa.gov/data/timeseries/month/': 'Pacific_Hurricane_Days'}, inplace=True)

In [30]:
# change year data to date format
df3['Date'] = pd.to_datetime(df3['Date'])

# filter the data to only include data from 1971 onwards
df_filtered2 = df3[df3['Date'] >= '1971-01-01']

# get the year from the date
df_filtered2['Year'] = df_filtered2['Date'].dt.year

# group by year and get the sum
yearly_avg2 = df_filtered2.groupby('Year')['Pacific_Hurricane_Days'].sum().reset_index()

# rename the columns for clarity
yearly_avg2.columns = ['Year', 'Pacific_Hurricane_Days']
df_3 = yearly_avg2

In [31]:
# merge with previous datasets
merged_df2 = pd.merge(merged_df, df_3, on='Year')

In [32]:
# add new column with the sum of pacific and atlantic hurricane days
merged_df2['Total_Hurricane_Days'] = merged_df2['Pacific_Hurricane_Days'] + merged_df2['Atlantic_Hurricane_Days']

In [33]:
# load new dataset for population
df_pop = pd.read_csv('/content/Project2_DS4002/DATA/Individual Datasets/population (1).csv')

In [34]:
# rename and drop columns for clarity
df_pop.rename(columns={'Population (historical)': 'Population'}, inplace=True)
df_pop.drop(columns=['Code'], inplace=True)

In [35]:
# filter for years and drop column
population_df = df_pop[(df_pop['Entity'] == 'World') & (df_pop['Year'] >= 1971) & (df_pop['Year'] <= 2021)]
population_df.drop(columns=['Entity'], inplace=True)

<ipython-input-35-bdcc37c15659>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population_df.drop(columns=['Entity'], inplace=True)

In [36]:
# merge data
merged_df3 = pd.merge(merged_df2, population_df, on='Year')

,Year,Atlantic_Hurricane_Days,CO2_emissions,Pacific_Hurricane_Days,Total_Hurricane_Days,Population
0,1971,28.75,1.550279e+10,38.50,67.25,3769847834
1,1972,6.25,1.622344e+10,33.75,40.00,3844917687
2,1973,10.00,1.708350e+10,28.50,38.50,3920805030
3,1974,14.25,1.700938e+10,22.75,37.00,3996416108
4,1975,20.50,1.704998e+10,26.75,47.25,4070735264
5,1976,25.50,1.798524e+10,27.25,52.75,4144246391
6,1977,6.75,1.849465e+10,5.25,12.00,4217863819
7,1978,13.50,1.906396e+10,51.50,65.00,4292097508
8,1979,21.75,1.960300e+10,13.75,35.50,4368539472
9,1980,38.25,1.948244e+10,22.75,61.00,4447606208
10,1981,22.50,1.901695e+10,18.25,40.75,4528777285
11,1982,5.75,1.886537e+10,39.25,45.00,4612673436
12,1983,3.50,1.898590e+10,47.75,51.25,4697327604
13,1984,18.25,1.964173e+10,46.25,64.50,4782175500
14,1985,21.25,2.030513e+10,49.75,71.00,4868943460
15,1986,10.50,2.060752e+10,28.75,39.25,4958072822
16,1987,5.00,2.124578e+10,29.50,34.50,5049746378
17,1988,21.25,2.207738e+10,29.50,50.75,5141992550
18,1989,31.75,2.237897e+10,27.25,59.00,5234431714
19,1990,26.75,2.275270e+10,58.25,85.00,5327803075
20,1991,8.25,2.322948e+10,44.00,52.25,5418735879
21,1992,16.00,2.256720e+10,65.50,81.50,5505989821
22,1993,9.50,2.279835e+10,50.75,60.25,5591544841
23,1994,7.25,2.303478e+10,33.00,40.25,5675551281
24,1995,60.25,2.352449e+10,22.25,82.50,5758878997
25,1996,45.00,2.425016e+10,13.00,58.00,5842055726
26,1997,9.50,2.439595e+10,33.50,43.00,5924787787
27,1998,48.50,2.433094e+10,33.00,81.50,6007066714
28,1999,41.00,2.483350e+10,23.50,64.50,6089006330
29,2000,32.75,2.550129e+10,16.75,49.50,6171703018
30,2001,25.50,2.567493e+10,18.50,44.00,6254936479
31,2002,10.75,2.624829e+10,26.00,36.75,6337730319
32,2003,32.75,2.764865e+10,11.00,43.75,6420361649
33,2004,45.50,2.862019e+10,14.00,59.50,6503377778
34,2005,49.75,2.959210e+10,23.50,73.25,6586970145
35,2006,21.25,3.060577e+10,34.00,55.25,6671452018
36,2007,12.25,3.149974e+10,8.75,21.00,6757308750
37,2008,30.50,3.204190e+10,19.00,49.50,6844457675
38,2009,12.00,3.149326e+10,23.00,35.00,6932766459
39,2010,38.50,3.330633e+10,11.50,50.00,7021732131
40,2011,26.00,3.443647e+10,26.75,52.75,7110923797
41,2012,28.50,3.493545e+10,21.50,50.00,7201202531
42,2013,3.25,3.523247e+10,14.50,17.75,7291793608
43,2014,17.75,3.546620e+10,44.50,62.25,7381616239
44,2015,12.00,3.546321e+10,62.25,74.25,7470491904
45,2016,27.75,3.546003e+10,38.50,66.25,7558554580
46,2017,51.75,3.602546e+10,20.00,71.75,7645618013
47,2018,27.50,3.676694e+10,68.25,95.75,7729902724
48,2019,23.50,3.704010e+10,16.75,40.25,7811293714
49,2020,35.25,3.500774e+10,14.25,49.50,7887001284
50,2021,27.75,3.681654e+10,21.50,49.25,7954448405

In [37]:
# load in sea level dataset
sealevel_df = pd.read_csv('/content/Project2_DS4002/DATA/Individual Datasets/sea-level_fig-1.csv')

In [38]:
# rename column for clarity
sealevel_df.rename(columns={'Figure 1. Global Average Absolute Sea Level Change, 1880-2023': 'Year'}, inplace=True)

In [39]:
# drop first 5 rows, these are just info about the dataset (not actual data we want to include)
dfsea_dropped = sealevel_df.drop(sealevel_df.index[:5])

In [40]:
# show column names
column_names = dfsea_dropped.columns.tolist()
print(column_names)

['Year', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

In [41]:
# drop extraneous columns and first row
dfsea_dropped.rename(columns={'Unnamed: 1': 'CSIRO_Adjusted_SeaLevel_Inch'}, inplace=True)
dfsea_dropped.drop(columns=['Unnamed: 2'], inplace=True)
dfsea_dropped.drop(columns=['Unnamed: 3'], inplace=True)
dfsea_dropped.drop(columns=['Unnamed: 4'], inplace=True)
dfsea_dropped = dfsea_dropped.drop(dfsea_dropped.index[:1])

In [42]:
# change the string type year data to integers
dfsea_dropped['Year'] = dfsea_dropped['Year'].astype(int)

In [43]:
# filter the years we want
sealevel_filtered = dfsea_dropped[(dfsea_dropped['Year'] >= 1971) & (dfsea_dropped['Year'] <= 2021)]

In [45]:
# merge data
merged_df4 = pd.merge(merged_df3, sealevel_filtered, on='Year')

,Year,Atlantic_Hurricane_Days,CO2_emissions,Pacific_Hurricane_Days,Total_Hurricane_Days,Population,CSIRO_Adjusted_SeaLevel_Inch
0,1971,28.75,1.550279e+10,38.50,67.25,3769847834,4.881889759
1,1972,6.25,1.622344e+10,33.75,40.00,3844917687,5.240157475
2,1973,10.00,1.708350e+10,28.50,38.50,3920805030,5.003937003
3,1974,14.25,1.700938e+10,22.75,37.00,3996416108,5.472440939
4,1975,20.50,1.704998e+10,26.75,47.25,4070735264,5.409448813
5,1976,25.50,1.798524e+10,27.25,52.75,4144246391,5.370078735
6,1977,6.75,1.849465e+10,5.25,12.00,4217863819,5.303149601
7,1978,13.50,1.906396e+10,51.50,65.00,4292097508,5.555118105
8,1979,21.75,1.960300e+10,13.75,35.50,4368539472,5.362204719
9,1980,38.25,1.948244e+10,22.75,61.00,4447606208,5.598425191
10,1981,22.50,1.901695e+10,18.25,40.75,4528777285,6.086614167
11,1982,5.75,1.886537e+10,39.25,45.00,4612673436,5.858267711
12,1983,3.50,1.898590e+10,47.75,51.25,4697327604,6.188976372
13,1984,18.25,1.964173e+10,46.25,64.50,4782175500,6.153543301
14,1985,21.25,2.030513e+10,49.75,71.00,4868943460,5.74803149
15,1986,10.50,2.060752e+10,28.75,39.25,4958072822,5.771653537
16,1987,5.00,2.124578e+10,29.50,34.50,5049746378,5.795275585
17,1988,21.25,2.207738e+10,29.50,50.75,5141992550,5.980314955
18,1989,31.75,2.237897e+10,27.25,59.00,5234431714,6.157480309
19,1990,26.75,2.275270e+10,58.25,85.00,5327803075,6.24803149
20,1991,8.25,2.322948e+10,44.00,52.25,5418735879,6.346456686
21,1992,16.00,2.256720e+10,65.50,81.50,5505989821,6.374015742
22,1993,9.50,2.279835e+10,50.75,60.25,5591544841,6.3031496
23,1994,7.25,2.303478e+10,33.00,40.25,5675551281,6.507874009
24,1995,60.25,2.352449e+10,22.25,82.50,5758878997,6.622047237
25,1996,45.00,2.425016e+10,13.00,58.00,5842055726,6.78346456
26,1997,9.50,2.439595e+10,33.50,43.00,5924787787,7.059055111
27,1998,48.50,2.433094e+10,33.00,81.50,6007066714,6.669291332
28,1999,41.00,2.483350e+10,23.50,64.50,6089006330,7.003937001
29,2000,32.75,2.550129e+10,16.75,49.50,6171703018,7.055118103
30,2001,25.50,2.567493e+10,18.50,44.00,6254936479,7.271653536
31,2002,10.75,2.624829e+10,26.00,36.75,6337730319,7.366141725
32,2003,32.75,2.764865e+10,11.00,43.75,6420361649,7.728346449
33,2004,45.50,2.862019e+10,14.00,59.50,6503377778,7.712598417
34,2005,49.75,2.959210e+10,23.50,73.25,6586970145,7.716535425
35,2006,21.25,3.060577e+10,34.00,55.25,6671452018,7.885826764
36,2007,12.25,3.149974e+10,8.75,21.00,6757308750,7.960629913
37,2008,30.50,3.204190e+10,19.00,49.50,6844457675,8.303149598
38,2009,12.00,3.149326e+10,23.00,35.00,6932766459,8.531496054
39,2010,38.50,3.330633e+10,11.50,50.00,7021732131,8.83464566
40,2011,26.00,3.443647e+10,26.75,52.75,7110923797,8.897637786
41,2012,28.50,3.493545e+10,21.50,50.00,7201202531,9.244094479
42,2013,3.25,3.523247e+10,14.50,17.75,7291793608,8.913385818
43,2014,17.75,3.546620e+10,44.50,62.25,7381616239,8.717314463
44,2015,12.00,3.546321e+10,62.25,74.25,7470491904,9.061105473
45,2016,27.75,3.546003e+10,38.50,66.25,7558554580,9.193601372
46,2017,51.75,3.602546e+10,20.00,71.75,7645618013,9.242845802
47,2018,27.50,3.676694e+10,68.25,95.75,7729902724,9.340091693
48,2019,23.50,3.704010e+10,16.75,40.25,7811293714,9.594329444
49,2020,35.25,3.500774e+10,14.25,49.50,7887001284,9.699874064
50,2021,27.75,3.681654e+10,21.50,49.25,7954448405,9.886687548

In [46]:
# load in data for earth surface temp change
surface_df = pd.read_csv('/content/Project2_DS4002/DATA/Individual Datasets/Annual_Surface_Temperature_Change.csv')

In [47]:
# get the column names
column_names = surface_df.columns.tolist()
print(column_names)

['ObjectId', 'Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS_Code', 'CTS_Name', 'CTS_Full_Descriptor', 'F1961', 'F1962', 'F1963', 'F1964', 'F1965', 'F1966', 'F1967', 'F1968', 'F1969', 'F1970', 'F1971', 'F1972', 'F1973', 'F1974', 'F1975', 'F1976', 'F1977', 'F1978', 'F1979', 'F1980', 'F1981', 'F1982', 'F1983', 'F1984', 'F1985', 'F1986', 'F1987', 'F1988', 'F1989', 'F1990', 'F1991', 'F1992', 'F1993', 'F1994', 'F1995', 'F1996', 'F1997', 'F1998', 'F1999', 'F2000', 'F2001', 'F2002', 'F2003', 'F2004', 'F2005', 'F2006', 'F2007', 'F2008', 'F2009', 'F2010', 'F2011', 'F2012', 'F2013', 'F2014', 'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020', 'F2021', 'F2022']

In [48]:
# drop unneeded columns
surface_df.drop(columns=['ObjectId'],inplace=True)
surface_df.drop(columns=['ISO2'],inplace=True)
surface_df.drop(columns=['ISO3'],inplace=True)
surface_df.drop(columns=['Indicator'],inplace=True)
surface_df.drop(columns=['Unit'],inplace=True)
surface_df.drop(columns=['Source'],inplace=True)
surface_df.drop(columns=['CTS_Code'],inplace=True)
surface_df.drop(columns=['CTS_Name'],inplace=True)
surface_df.drop(columns=['CTS_Full_Descriptor'],inplace=True)

In [49]:
# filter just the world temperature
surface_filtered = surface_df[surface_df['Country'] == 'World']

In [51]:
# pivot the data and change the year variable to be the correct format and type
surface_filtered.columns = surface_filtered.columns.str.replace('F', '', regex=False)
melted_df = surface_filtered.melt(id_vars=['Country'], var_name='Year', value_name='Surface Temperature')

# filter for years between 1971 and 2021
filtered_sdf = melted_df[(melted_df['Year'].astype(int) >= 1971) & (melted_df['Year'].astype(int) <= 2021)]

# drop the country column (we only need year and surface temperature)
filtered_sdf = filtered_sdf.drop(columns=['Country'])

In [52]:
# make year into an int
filtered_sdf['Year'] = filtered_sdf['Year'].astype(int)

In [53]:
# rename column
filtered_sdf.rename(columns={'Surface Temperature': 'Surface_Temperature_Change'}, inplace=True)

In [54]:
# merge data
merged_df5 = pd.merge(merged_df4, filtered_sdf, on='Year')

,Year,Atlantic_Hurricane_Days,CO2_emissions,Pacific_Hurricane_Days,Total_Hurricane_Days,Population,CSIRO_Adjusted_SeaLevel_Inch,Surface_Temperature_Change
0,1971,28.75,1.550279e+10,38.50,67.25,3769847834,4.881889759,-0.093
1,1972,6.25,1.622344e+10,33.75,40.00,3844917687,5.240157475,-0.199
2,1973,10.00,1.708350e+10,28.50,38.50,3920805030,5.003937003,0.269
3,1974,14.25,1.700938e+10,22.75,37.00,3996416108,5.472440939,-0.181
4,1975,20.50,1.704998e+10,26.75,47.25,4070735264,5.409448813,0.088
5,1976,25.50,1.798524e+10,27.25,52.75,4144246391,5.370078735,-0.314
6,1977,6.75,1.849465e+10,5.25,12.00,4217863819,5.303149601,0.269
7,1978,13.50,1.906396e+10,51.50,65.00,4292097508,5.555118105,0.001
8,1979,21.75,1.960300e+10,13.75,35.50,4368539472,5.362204719,0.226
9,1980,38.25,1.948244e+10,22.75,61.00,4447606208,5.598425191,0.332
10,1981,22.50,1.901695e+10,18.25,40.75,4528777285,6.086614167,0.443
11,1982,5.75,1.886537e+10,39.25,45.00,4612673436,5.858267711,0.086
12,1983,3.50,1.898590e+10,47.75,51.25,4697327604,6.188976372,0.460
13,1984,18.25,1.964173e+10,46.25,64.50,4782175500,6.153543301,0.127
14,1985,21.25,2.030513e+10,49.75,71.00,4868943460,5.74803149,-0.031
15,1986,10.50,2.060752e+10,28.75,39.25,4958072822,5.771653537,0.242
16,1987,5.00,2.124578e+10,29.50,34.50,5049746378,5.795275585,0.403
17,1988,21.25,2.207738e+10,29.50,50.75,5141992550,5.980314955,0.558
18,1989,31.75,2.237897e+10,27.25,59.00,5234431714,6.157480309,0.331
19,1990,26.75,2.275270e+10,58.25,85.00,5327803075,6.24803149,0.639
20,1991,8.25,2.322948e+10,44.00,52.25,5418735879,6.346456686,0.468
21,1992,16.00,2.256720e+10,65.50,81.50,5505989821,6.374015742,0.184
22,1993,9.50,2.279835e+10,50.75,60.25,5591544841,6.3031496,0.348
23,1994,7.25,2.303478e+10,33.00,40.25,5675551281,6.507874009,0.507
24,1995,60.25,2.352449e+10,22.25,82.50,5758878997,6.622047237,0.835
25,1996,45.00,2.425016e+10,13.00,58.00,5842055726,6.78346456,0.355
26,1997,9.50,2.439595e+10,33.50,43.00,5924787787,7.059055111,0.656
27,1998,48.50,2.433094e+10,33.00,81.50,6007066714,6.669291332,0.993
28,1999,41.00,2.483350e+10,23.50,64.50,6089006330,7.003937001,0.783
29,2000,32.75,2.550129e+10,16.75,49.50,6171703018,7.055118103,0.728
30,2001,25.50,2.567493e+10,18.50,44.00,6254936479,7.271653536,0.834
31,2002,10.75,2.624829e+10,26.00,36.75,6337730319,7.366141725,1.021
32,2003,32.75,2.764865e+10,11.00,43.75,6420361649,7.728346449,0.893
33,2004,45.50,2.862019e+10,14.00,59.50,6503377778,7.712598417,0.913
34,2005,49.75,2.959210e+10,23.50,73.25,6586970145,7.716535425,1.095
35,2006,21.25,3.060577e+10,34.00,55.25,6671452018,7.885826764,0.998
36,2007,12.25,3.149974e+10,8.75,21.00,6757308750,7.960629913,1.195
37,2008,30.50,3.204190e+10,19.00,49.50,6844457675,8.303149598,0.935
38,2009,12.00,3.149326e+10,23.00,35.00,6932766459,8.531496054,0.957
39,2010,38.50,3.330633e+10,11.50,50.00,7021732131,8.83464566,1.219
40,2011,26.00,3.443647e+10,26.75,52.75,7110923797,8.897637786,0.921
41,2012,28.50,3.493545e+10,21.50,50.00,7201202531,9.244094479,1.074
42,2013,3.25,3.523247e+10,14.50,17.75,7291793608,8.913385818,1.016
43,2014,17.75,3.546620e+10,44.50,62.25,7381616239,8.717314463,1.053
44,2015,12.00,3.546321e+10,62.25,74.25,7470491904,9.061105473,1.412
45,2016,27.75,3.546003e+10,38.50,66.25,7558554580,9.193601372,1.660
46,2017,51.75,3.602546e+10,20.00,71.75,7645618013,9.242845802,1.429
47,2018,27.50,3.676694e+10,68.25,95.75,7729902724,9.340091693,1.290
48,2019,23.50,3.704010e+10,16.75,40.25,7811293714,9.594329444,1.444
49,2020,35.25,3.500774e+10,14.25,49.50,7887001284,9.699874064,1.711
50,2021,27.75,3.681654e+10,21.50,49.25,7954448405,9.886687548,1.447

In [55]:
# import next dataset for sea temp change
seatemp_df = pd.read_csv('/content/Project2_DS4002/DATA/Individual Datasets/sea-surface-temp_fig-1.csv', encoding='ISO-8859-1')

In [56]:
# get the column names
column_names = seatemp_df.columns.tolist()
print(column_names)

['Figure 1. Average Global Sea Surface Temperature, 1880-2023', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

In [57]:
# rename column
seatemp_df.rename(columns={'Figure 1. Average Global Sea Surface Temperature, 1880-2023': 'Year'}, inplace=True)

In [58]:
# drop into added to top of dataset
seatemp_dropped = seatemp_df.drop(seatemp_df.index[:5])

In [59]:
# drop unneeded columns
seatemp_dropped.drop(columns=['Unnamed: 2'], inplace=True)
seatemp_dropped.drop(columns=['Unnamed: 3'], inplace=True)
seatemp_dropped.rename(columns={'Unnamed: 1': 'SurfaceSeaTemp_Annual_Anomaly'}, inplace=True)

In [60]:
# drop top column
seatemp_dropped = seatemp_dropped.drop(seatemp_dropped.index[:1])

In [61]:
# make year into an int
seatemp_dropped['Year'] = seatemp_dropped['Year'].astype(int)

In [62]:
# filter for years we want
seatemp_data = seatemp_dropped[(seatemp_dropped['Year'] >= 1971) & (seatemp_dropped['Year'] <= 2021)]

In [64]:
# merge data
hurricane_data = pd.merge(merged_df5, seatemp_data, on='Year')

In [65]:
# swap order of the columns for clarity
cols = hurricane_data.columns.tolist()
cols[2], cols[3] = cols[3], cols[2]
hurricane_data = hurricane_data[cols]

In [66]:
# swap order of the columns for clarity
cols2 = hurricane_data.columns.tolist()
cols2[3], cols2[4] = cols2[4], cols2[3]
hurricane_data = hurricane_data[cols2]

In [67]:
hurricane_data

,Year,Atlantic_Hurricane_Days,Pacific_Hurricane_Days,Total_Hurricane_Days,CO2_emissions,Population,CSIRO_Adjusted_SeaLevel_Inch,Surface_Temperature_Change,SurfaceSeaTemp_Annual_Anomaly
0,1971,28.75,38.50,67.25,1.550279e+10,3769847834,4.881889759,-0.093,-0.519
1,1972,6.25,33.75,40.00,1.622344e+10,3844917687,5.240157475,-0.199,-0.193
2,1973,10.00,28.50,38.50,1.708350e+10,3920805030,5.003937003,0.269,-0.151
3,1974,14.25,22.75,37.00,1.700938e+10,3996416108,5.472440939,-0.181,-0.427
4,1975,20.50,26.75,47.25,1.704998e+10,4070735264,5.409448813,0.088,-0.445
5,1976,25.50,27.25,52.75,1.798524e+10,4144246391,5.370078735,-0.314,-0.358
6,1977,6.75,5.25,12.00,1.849465e+10,4217863819,5.303149601,0.269,-0.072
7,1978,13.50,51.50,65.00,1.906396e+10,4292097508,5.555118105,0.001,-0.18
8,1979,21.75,13.75,35.50,1.960300e+10,4368539472,5.362204719,0.226,0.039
9,1980,38.25,22.75,61.00,1.948244e+10,4447606208,5.598425191,0.332,0.065
10,1981,22.50,18.25,40.75,1.901695e+10,4528777285,6.086614167,0.443,0
11,1982,5.75,39.25,45.00,1.886537e+10,4612673436,5.858267711,0.086,0
12,1983,3.50,47.75,51.25,1.898590e+10,4697327604,6.188976372,0.460,0.137
13,1984,18.25,46.25,64.50,1.964173e+10,4782175500,6.153543301,0.127,-0.034
14,1985,21.25,49.75,71.00,2.030513e+10,4868943460,5.74803149,-0.031,-0.106
15,1986,10.50,28.75,39.25,2.060752e+10,4958072822,5.771653537,0.242,-0.049
16,1987,5.00,29.50,34.50,2.124578e+10,5049746378,5.795275585,0.403,0.214
17,1988,21.25,29.50,50.75,2.207738e+10,5141992550,5.980314955,0.558,0.14
18,1989,31.75,27.25,59.00,2.237897e+10,5234431714,6.157480309,0.331,0.068
19,1990,26.75,58.25,85.00,2.275270e+10,5327803075,6.24803149,0.639,0.246
20,1991,8.25,44.00,52.25,2.322948e+10,5418735879,6.346456686,0.468,0.183
21,1992,16.00,65.50,81.50,2.256720e+10,5505989821,6.374015742,0.184,0.041
22,1993,9.50,50.75,60.25,2.279835e+10,5591544841,6.3031496,0.348,0.052
23,1994,7.25,33.00,40.25,2.303478e+10,5675551281,6.507874009,0.507,0.09
24,1995,60.25,22.25,82.50,2.352449e+10,5758878997,6.622047237,0.835,0.169
25,1996,45.00,13.00,58.00,2.425016e+10,5842055726,6.78346456,0.355,0.086
26,1997,9.50,33.50,43.00,2.439595e+10,5924787787,7.059055111,0.656,0.353
27,1998,48.50,33.00,81.50,2.433094e+10,6007066714,6.669291332,0.993,0.441
28,1999,41.00,23.50,64.50,2.483350e+10,6089006330,7.003937001,0.783,0.079
29,2000,32.75,16.75,49.50,2.550129e+10,6171703018,7.055118103,0.728,0.129
30,2001,25.50,18.50,44.00,2.567493e+10,6254936479,7.271653536,0.834,0.356
31,2002,10.75,26.00,36.75,2.624829e+10,6337730319,7.366141725,1.021,0.41
32,2003,32.75,11.00,43.75,2.764865e+10,6420361649,7.728346449,0.893,0.453
33,2004,45.50,14.00,59.50,2.862019e+10,6503377778,7.712598417,0.913,0.434
34,2005,49.75,23.50,73.25,2.959210e+10,6586970145,7.716535425,1.095,0.428
35,2006,21.25,34.00,55.25,3.060577e+10,6671452018,7.885826764,0.998,0.426
36,2007,12.25,8.75,21.00,3.149974e+10,6757308750,7.960629913,1.195,0.293
37,2008,30.50,19.00,49.50,3.204190e+10,6844457675,8.303149598,0.935,0.27
38,2009,12.00,23.00,35.00,3.149326e+10,6932766459,8.531496054,0.957,0.493
39,2010,38.50,11.50,50.00,3.330633e+10,7021732131,8.83464566,1.219,0.511
40,2011,26.00,26.75,52.75,3.443647e+10,7110923797,8.897637786,0.921,0.32
41,2012,28.50,21.50,50.00,3.493545e+10,7201202531,9.244094479,1.074,0.441
42,2013,3.25,14.50,17.75,3.523247e+10,7291793608,8.913385818,1.016,0.48
43,2014,17.75,44.50,62.25,3.546620e+10,7381616239,8.717314463,1.053,0.646
44,2015,12.00,62.25,74.25,3.546321e+10,7470491904,9.061105473,1.412,0.858
45,2016,27.75,38.50,66.25,3.546003e+10,7558554580,9.193601372,1.660,0.93
46,2017,51.75,20.00,71.75,3.602546e+10,7645618013,9.242845802,1.429,0.821
47,2018,27.50,68.25,95.75,3.676694e+10,7729902724,9.340091693,1.290,0.741
48,2019,23.50,16.75,40.25,3.704010e+10,7811293714,9.594329444,1.444,0.878
49,2020,35.25,14.25,49.50,3.500774e+10,7887001284,9.699874064,1.711,0.846
50,2021,27.75,21.50,49.25,3.681654e+10,7954448405,9.886687548,1.447,0.668